# $ go get -u github.com/spf13/viper@v1.4.0
# Viper is a complete configuration solution for Go applications including 12-Factor apps.
# It is designed to work within an application,
# and can handle all types of configuration needs and formats. It supports:

Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:8080/static
  UploadImageMaxSize: 5  # MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
Database:
  DBType: mysql
  Username: root  # 填写你的数据库账号
  Password: 123456  # 填写你的数据库密码
  Host: 127.0.0.1:3310
  DBName: blog_service
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
JWT:
  Secret: qwe123hahaha
  Issuer: blog-service
  Expire: 7200
Email:
  Host: smtp.gmail.com
  Port: 465
  UserName: xxx@gmail.com
  Password: xxx
  IsSSL: true
  From: xxx@gmail.com
  To:
    - xxx@gmail.com